language: java
jdk: oraclejdk13
addons:
  apt:
    packages:
      - oracle-java13-installer
services:
  - mysql
before_install:
  - export TZ=Europe/Rome
  - cd src/urcoach
  - chmod +x mvnw
script:
  - mvn verify
