language: java
jdk: oraclejdk13
services:
  - mysql
before_install:
  - export TZ=Europe/Rome
  - cd src/urcoach
  - chmod +x mvnw
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('salvatore') WHERE user='root';\nFLUSH PRIVILEGES;\n"
script:
  - mvn verify
after_success:
  - mvn jacoco:report
  - bash <(curl -s https://codecov.io/bash) -t 24de1408-eb5d-41e4-b4fe-5fcf786e7043
