language: java
jdk: oraclejdk13
services:
  - mysql
before_install:
  - export TZ=Europe/Rome
  - cd src/urcoach
  - chmod +x mvnw
script:
   - export JAVA_HOME=$HOME/oraclejdk13
  - $TRAVIS_BUILD_DIR/install-jdk.sh --install oraclejdk13 --target $JAVA_HOME
  - mvn verify
